### ISSUE TITLE
Plans for release?

### ISSUE THREAD

**Issue by daniel2887** [jmding8/MercuryKeyboard#1]
Hi!

I've been looking for a row staggered corne-like keyboard for a while and this seems like a great fit. Any plans for releasing the PCBs and ZMK firmware source?

Thank you

**Comment by jmding8** [comment]
Thank you for expressing interest, it's hugely motivating! I'll work on getting this released soon. Keep pestering me if it doesn't happen soon

**Comment by jmding8** [comment]
@daniel2887 PCB files and manufacturing information have been uploaded!

**Comment by daniel2887** [comment]
Awesome! Thank you for following up, and for the super detailed build guide and BOM. I really like how you minimized Z height cutting out a piece of the PCB to make room for the battery.

Couple of questions/comments:
1. It would help to split up the case file so that each half can be printed separately. (I was able to delete one of the 2 pairs in Cura, but the remaining pair is too wide for common ~235 mm^2 build plates such as Ender 3 variants)
2. What's the difference between the two case pairs? One of them is a bit thicker it seems.
3. How thick does the keyboard end up being from the bottom of the bottom plate to the top of the top plate?
4. The Firmware link from the build guide is broken (the link in [this section](https://github.com/jmding8/MercuryKeyboard/blob/main/text/build_guide.md#firmware)).
5. For folks who would like to modify the firmware/keymap, it would be helpful to include a link to [your fork](https://github.com/jmding8/zmk) of ZMK (based on the commits there I'm assuming that's what I should be compiling :-) )

**Comment by jmding8** [comment]
thank you for the feedback!
1. updated
2. Yes, low-profile and full-height. I added a note about this in the manufacturing notes
3. 19mm from table to typing-surface with MBK keycaps. I added a note about this in the readme
4. fixed!
5. makes sense! I'll work on getting the shield merged into ZMK main as well, so people can compile using their GHA workflow

**Comment by daniel2887** [comment]
Thank you! Closing out this issue -- thank you again for releasing the gerber files and docs! I will give the build a try and post back if I run into issues :)

**Comment by jmding8** [comment]
Excited to hear that!
